apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-deployment
  labels:
    app: wil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil
  template:
    metadata:
      labels:
        app: wil
    spec:
      containers:
      - name: wil-image
        image: wil42/playground:v2
        ports:
        - containerPort: 8888

---

apiVersion: apps/v1
kind: Service
metadata:
  name: wil-service
  namespace: dev
spec:
  selector:
    matchLabels:
      app: wil
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer

